Add job details for eda-server usage
ansible/ansible-rulebook pull request #166
Opened 2022-09-26 19:49 UTC by hsong-rh

Add more job related details to the event queue, so EDA server side can save them for either debug or job rerun.

Resolves: [AAP-5081](https://issues.redhat.com/browse/AAP-5081)

2022-10-12 17:11 UTC, mkanoor commented on ansible_rulebook/builtin.py
> +            ruleset=ruleset,
@hsong-rh This should be the source_ruleset_name

2022-10-12 17:12 UTC, mkanoor commented on tests/test_rules.py
> +    assert ruleset_queue_plans[0][2].get_nowait().action == "slack"
@hsong-rh Can one of these tests be modified to check the ruleset name and the rule name?

2022-10-12 20:54 UTC, mkanoor requested changes
Use the correct ruleset the current implementation breaks when using multiple rulesets

2022-10-12 21:16 UTC, mkanoor commented on ansible_rulebook/builtin.py
> +    source_ruleset_name: str,
@hsong-rh This seems to be off by one
The ruleset should be after source_ruleset_name and source_rule_name

2022-10-13 15:02 UTC, mkanoor approved these changes

2022-10-13 21:15 UTC, hsong-rh commented
@benthomasson can you review and merge this? thanks

2022-10-14 12:01 UTC, cutwater approved these changes

2022-10-14 12:02 UTC, merged