Support for standalone booleans in conditions
ansible/ansible-rulebook pull request #297
Opened 2023-01-18 21:27 UTC by mkanoor

This helps when we want to print events without knowing the contents of the event.
The literal boolean true allows the condition to pass and the action print_event can be used to print the event

This would usually be used for bulding the rulebook, you would not use it in production.

```
    - name: print event always
      condition: true
      action:
        print_event:
          pretty: true
```

2023-01-19 10:53 UTC, Alex-Izquierdo commented
I think this could be a good replacement for the --print-all-events flag, isn't? @benthomasson 
https://issues.redhat.com/browse/AAP-8089

I personally prefer a statement in the rulebook instead of a flag.

2023-01-19 10:53 UTC, Alex-Izquierdo approved these changes

2023-01-19 15:40 UTC, benthomasson requested changes
I am not sure this is the right way to print events.

2023-01-19 18:00 UTC, closed without merging

2023-03-14 15:27 UTC, AssafKatz3 commented
Hi @Alex-Izquierdo and @benthomasson,
I have another use case for it - we want to process all Kafka events on a topic.  And I believe that we will have more use cases for this option.
Thanks

2023-03-14 16:55 UTC, Alex-Izquierdo commented
Hi @AssafKatz3 I suggest to open a new feature request for it. Anyway, this is currently possible. 
You can write a condition that will always match. So, if you events will contain a name field, you can use `event.name is defined`

Even if the schema of your events is dynamic and you can not ensure the existence of a certain field, you can write your own filter to add it.

2023-03-15 07:07 UTC, AssafKatz3 commented
@Alex-Izquierdo I opened [feature request](https://github.com/ansible/ansible-rulebook/issues/443). I couldn't find any instructions for custom filters.