[AAP-9251] Fixed exclusion of disabled rules
ansible/ansible-rulebook pull request #363
Opened 2023-02-13 19:51 UTC by mkanoor

A rule can optionally be disabled by setting enabled=false. This is handy when testing and certain rules need to be disabled temporarily. Fixed the json schema, added an example.

https://issues.redhat.com/browse/AAP-9251

2023-02-13 20:59 UTC, Alex-Izquierdo commented
eda-controller must be updated as well: https://issues.redhat.com/browse/AAP-9257

2023-02-13 21:00 UTC, Alex-Izquierdo approved these changes

2023-02-13 21:02 UTC, Alex-Izquierdo requested changes

2023-02-13 21:02 UTC, Alex-Izquierdo commented on docs/rules.rst
> +            enable: false
typo: is `enabled`

2023-02-13 22:03 UTC, mkanoor commented
@Alex-Izquierdo Fixed typo

2023-02-14 06:10 UTC, ttuffin approved these changes

2023-02-14 06:11 UTC, merged