[AAP-9309] Add support for Null type
ansible/ansible-rulebook pull request #379
Opened 2023-02-18 21:15 UTC by mkanoor

The event payload could contain null values which might have to be compared.

https://issues.redhat.com/browse/AAP-9309

2023-02-20 09:27 UTC, Alex-Izquierdo requested changes
Changelog must be updated also.

2023-02-21 19:12 UTC, Alex-Izquierdo submitted a review, later dismissed

2023-02-23 00:15 UTC, mkanoor commented
@Alex-Izquierdo @ttuffin Please review

2023-02-23 08:56 UTC, Alex-Izquierdo approved these changes

2023-02-23 09:48 UTC, ttuffin approved these changes

2023-02-23 09:48 UTC, merged