Added example of multiple conditions
ansible/ansible-rulebook pull request #474
Opened 2023-04-11 22:11 UTC by mkanoor

Multiple conditions have special handling in Drools which keep the events in cache till they are used and then re-evaluated when the events match.

2023-04-12 12:18 UTC, ttuffin requested changes

2023-04-12 12:18 UTC, ttuffin commented on docs/conditions.rst
> +        Note that in this case the engine will consider **all the different events** until meet the conditions,
```suggestion
        Note that in this case the engine will consider **all the different events** until the conditions are met,
```

2023-04-12 12:18 UTC, ttuffin commented on docs/conditions.rst
> +        Note that in this case the engine will consider **all the different events** until one of then meets one of the condition,
```suggestion
        Note that in this case the engine will consider **all the different events** until one of them meets one of the conditions,
```

2023-04-18 10:17 UTC, Alex-Izquierdo approved these changes

2023-04-18 10:49 UTC, merged