feat: support firing of multiple rules
ansible/ansible-rulebook pull request #565
Opened 2023-08-06 19:33 UTC by mkanoor

https://issues.redhat.com/browse/AAP-13076

Drools has always supported firing of multiple rules when an event or a fact comes in. Durable rules only supported this behavior for facts but not for events. This PR adds a feature to a ruleset to indicate if it should match_multiple rules. The default is false

2023-08-08 16:31 UTC, Alex-Izquierdo commented
This PR doesn't require an upgrade of drools-jpy? I believe it depends of some PR to be merged in the drools-integration project.

2023-08-08 16:31 UTC, Alex-Izquierdo requested changes
Release notes update missing.

2023-08-08 16:35 UTC, mkanoor commented
@Alex-Izquierdo this was added in drools-jpy via https://issues.redhat.com/browse/AAP-13076, the current drools_jpy already has this change, we don't need a new drools-jpy

2023-08-08 19:14 UTC, Alex-Izquierdo submitted a review, later dismissed
I really think it should have some e2e test as well, regardless of that LGTM

2023-08-08 19:16 UTC, Alex-Izquierdo commented on ansible_rulebook/rule_types.py
> +    match_multiple_rules: Optional[bool] = False
Minor: type hint is wrong. If the value is not nullable, it should not be optional.
```suggestion
    match_multiple_rules: bool = False
```

2023-08-09 13:14 UTC, ttuffin commented
> I really think it should have some e2e test as well, regardless of that LGTM

+1. It would be great if any new features for rulebook will have coverage added to the e2e tests.

2023-08-21 14:57 UTC, mkanoor commented
@Alex-Izquierdo @ttuffin I have added the e2e tests

2023-08-22 14:17 UTC, benthomasson commented
@mkanoor this exposes a bug in the Rule Audit view assumptions.   This page is rule-focused and requires hunting for the event that caused the rule to fire instead of being event centric and showing what rules and actions fired from that event.

2023-08-22 14:20 UTC, benthomasson commented
We should hold off on merging this until we have a meeting to discuss the Rule Audit view.

2023-08-22 15:19 UTC, benthomasson approved these changes

2023-08-22 17:06 UTC, merged